version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${DUCKDNS_URL}
      - SUBDOMAINS=<wildcard/subdomain1,subdomain2>
      - VALIDATION=<http/dns/duckdns>
      - DUCKDNS_TOKEN=${DUCK_TOKEN} #optional unless using duckdns validation
    volumes:
      - /home/<user>/appdata/letsencrypt:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SUBDOMAINS=subdomain1,subdomain2
      - DUCKDNS_TOKEN=<token>
      - LOG_FILE=false #optional
    volumes:
      - /home/<user>/appdata/duckdns:/config #optional unless LOG_FILE set to true
    restart: unless-stopped
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - /home/<user>/appdata/duplicati:/config
      - /home/<user>/appdata/duplicati/backups:/backups #recommended to point to a mounted server
      - /home/<user>:/source
    ports:
      - 8200:8200
    restart: unless-stopped
