version: "3"

services:

# Environment variables can be found in /etc/environment

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${URL}
      # - URL=${DUCKDNS_URL}
      - SUBDOMAINS=wildcard
      # - VALIDATION=duckdns
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      # - DUCKDNSTOKEN=${DUCKDNS_TOKEN} # optional unless using duckdns validation
      # - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  # duckdns:
  #   image: ghcr.io/linuxserver/duckdns
  #   container_name: duckdns
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #     - SUBDOMAINS=shariq-dev
  #     - TOKEN=${DUCKDNS_TOKEN}
  #     - LOG_FILE=false # optional
  #   volumes:
  #     - ./appdata/duckdns:/config # optional unless LOG_FILE set to true
  #   restart: unless-stopped

  # duplicati:
  #   image: ghcr.io/linuxserver/duplicati
  #   container_name: duplicati
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #     # - CLI_ARGS= # optional
  #   volumes:
  #     - ./appdata/duplicati:/config
  #     - ./appdata/duplicati/backups:/backups # recommended to point to a mounted server (I used the GUI to back up to Google Drive instead)
  #     - ./:/source
  #   ports:
  #     - 8200:8200
  #   restart: unless-stopped
    
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

# Stand up network named "default" which can be bound to in other compose files
networks:
  default:
    driver: bridge
    