version: "3"
services:  
  elaticsearch:    
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1    
    container_name: elasticsearch    
    environment:
      - node.name=es01
      - xpack.security.enabled=true # enabled to get basic auth, remove for anything else
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD} # bootstrap user `elastic` with the password defined
      - discovery.type=single-node # must set this to avoid bootstrap checks
      - bootstrap.memory_lock=true # stop memory swap
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # min and max heap size for the app
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/<user>/appdata/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: unless-stopped
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_URL=http://elasticsearch:9200 # calling elasticseach container through network by its name
    ports:
      - 5601:5601
    restart: unless-stopped
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
#    deploy: # need labels for the docker filebeat config to pick up logs here
#      labels:
#        com.example.description: "This label will appear on the logstash service"
    volumes:
      - /home/shariq/appdata/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /home/shariq/appdata/logstash/pipeline:/usr/share/logstash/pipeline
      # mount log files from nginx
      - /home/shariq/appdata/swag/log/nginx:/logstash_dir/nginx
    ports:
      - 5044:5044 # destination port for beats
    restart: unless-stopped
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.10.1
  #   container_name: filebeat
  #   user: root
  #   environment:
  #     - setup.kibana.host=kibana:5601 # calling kibana container through network by its name
  #     - output.elasticsearch.hosts=["elasticsearch:9200"] # calling elasticseach container through network by its name
  #     - strict.perms=false
  #   volumes:
  #     - /home/shariq/appdata/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     # needed to access all docker logs (read only) :
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     # needed to access additional informations about containers
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped
  # metricbeat: # not yet implemented
  #   image: docker.elastic.co/beats/metricbeat:7.10.1
  #   container_name: metricbeat
  #   environment:
  #     - setup.kibana.host=kibana:5601 # calling kibana container through network by its name
  #     - output.elasticsearch.hosts=["elasticsearch:9200"] # calling elasticseach container through network by its name
  #   volumes:
  #   ports:
  #   restart: unless-stopped
  