version: "3.3"

services:

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host # https://docs.docker.com/network/host/
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./appdata/plex:/config
      - /mnt/plex/TV Shows:/tv
      - /mnt/plex/Movies:/movies
    devices:
      - /dev/dri:/dev/dri #gives access to Intel Quicksync
    restart: unless-stopped

  transmission-openvpn:
    container_name: transmission-openvpn
    cap_add:
        - NET_ADMIN
    volumes:
        - ./appdata/transmission-openvpn:/data
    environment:
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=us_texas,us_houston,us_denver,us_chicago # One will be randomly selected at startup
        - OPENVPN_USERNAME=${PIA_USERNAME}
        - OPENVPN_PASSWORD=${PIA_PASSWORD}
        - LOCAL_NETWORK=192.168.86.0/24 # Allows defined IP range to access
        - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
        - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
        - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '9091:9091'
    image: haugene/transmission-openvpn
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/radarr:/config
      - /mnt/plex/Movies:/movies
      - ./appdata/transmission-openvpn/data/completed:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  # tautulli:
  #   image: tautulli/tautulli
  #   container_name: tautulli
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   volumes:
  #     - ./appdata/tautulli:/config
  #   ports:
  #     - 8181:8181
  #   restart: unless-stopped

  # ombi:
  #   image: ghcr.io/linuxserver/ombi
  #   container_name: ombi
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   volumes:
  #     - ./appdata/ombi:/config
  #   ports:
  #     - 3579:3579
  #   restart: unless-stopped

# add sonarr
# add radarr
# add bazarr(https://www.bazarr.media/)
# add jackett
