version: "3"

services:

  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./appdata/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

# add sonarr, radarr, and jackett for completeness in the future
