# https://raw.githubusercontent.com/elastic/beats/7.10/deploy/docker/filebeat.docker.yml

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false

processors:
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}' # TODO: make sure env vars are working, this seems odder than usual
  password: '${ELASTICSEARCH_PASSWORD:MagicPassword}'
